#pragma once

#include "quark.h"

typedef ObjectId HSObjId;
typedef uint64 HSClassId;
#define HSCALE_MAX_STRING_LENGTH 32
#define HSCALE_MAX_BUFFER_LENGTH 32

#define HSCALE_DEFAULT_RELIABLE_SEND_TICK_INTERVAL 60
#define HSCALE_DEFAULT_UNRELIABLE_SEND_TICK_INTERVAL 60

#define HSCALE_SUBSCRIPTION_SHORT_RADIUS 0.2
#define HSCALE_SUBSCRIPTION_SHORT_RADIUS_INTERVAL_MS 60
#define HSCALE_SUBSCRIPTION_LONG_RADIUS 0.8
#define HSCALE_SUBSCRIPTION_LONG_RADIUS_INTERVAL_MS 600

#define HS_EVENT_RADIUS_LOW 0.2f
#define HS_EVENT_RADIUS_MEDIUM 0.6f

#define HYPERSCALE_LEVEL_OPTION TEXT("hscale")
#define HYPERSCALE_ROLE_OPTION TEXT("Roles")

#define HSCALE_LOCAL_IP_ADDRESS TEXT("127.0.0.1")
#define HSCALE_MAX_ALLOWED_EDITOR_SERVERS 10

DECLARE_LOG_CATEGORY_EXTERN(Log_HyperScaleGlobals, Log, All);

DECLARE_LOG_CATEGORY_EXTERN(Log_HyperScaleReplication, Log, All);

DECLARE_LOG_CATEGORY_EXTERN(Log_HyperScaleEditor, Log, All);

DECLARE_LOG_CATEGORY_EXTERN(Log_HyperScaleEvents, Log, All);

#define HSCALE_DYNAMIC_ARRAY_CLASS_ID 1
